micronaut:
  application:
    name: keymanagerGrpc

datasources:
  default:
    url: jdbc:mysql://localhost:3306/pix?createDatabaseIfNotExist=true
    username: root
    password: "06071991"

jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update

itau:
    url: ${ITAU_URL:`http://localhost:9091`}

bcb:
  url: ${BCB_URL:`http://localhost:8082`}